### ISSUE TITLE
How far should this role go?

### ISSUE THREAD

**Issue by gregswift** [kost/ansible-galaxy.ubuntu.puppet#1]
I was about to put the effort into writing a puppet role for EL/Debian that would do the following:

a) add puppetlabs repo
b) install agent
c) basic agent config
d) enable agent
e) force run

I'd use tags so that bits and pieces could be used separately by consumers.  See my plight role for an example:

https://galaxy.ansible.com/list#/roles/621

Would you be interested in supporting this in this module? Or should I just make my own.

**Comment by kost** [comment]
This sounds good. Let's do it together!

**Comment by gregswift** [comment]
Awesome :)

**Comment by gregswift** [comment]
@kost have you gotten a chance to check out my proposed changes? Do you have any feedback?

**Comment by gregswift** [comment]
@kost so any thoughts on testing/path forward to get this updated in galaxy?

**Comment by kost** [comment]
I plan to thoroughly test it under ubuntu and debian this weekend and then
we can do it on galaxy?

What do you think about it?

On Fri, May 30, 2014 at 4:28 PM, Greg Swift notifications@github.com
wrote:

> @kost https://github.com/kost so any thoughts on testing/path forward
> to get this updated in galaxy?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kost/ansible-galaxy.ubuntu.puppet/issues/1#issuecomment-44656747
> .

## 

Vlatko Kosturjak, Kost

**Comment by gregswift** [comment]
Sounds great

**Comment by kost** [comment]
Tested and pushed to galaxy. Added your credit. Thanks for contributing.

**Comment by gregswift** [comment]
:100: yay! thanks
